name: Partie 1 - Découverte GitHub Actions

on: [push]

jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to me
        run: printf "Hello ${{ github.actor }} ! 🥳"

      - name: List files in the repository
        run: | # Le pipe (|) permet d'écrire du texte multilignes
          ls ${{ github.workspace }}

      - name: Ma commande Linux personnalisée
        run: echo "Date et heure actuelle : $(date)"
